### PR TITLE
Add mapping for RH managed services

### PR DESCRIPTION
**Pull request by gbenhaim**

### CODE REVIEW

**Review by scoheb — APPROVED** [review]

**Comment by scoheb** [comment]
@gbenhaim we need signed commits on this repo.

**Comment by gbenhaim** [comment]
@scoheb signed with which key?

**Comment by davidmogar** [comment]
Yours https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by gbenhaim** [comment]
@scoheb @davidmogar done

**Pull request merged**
