### PR TITLE
feat: add new strategies

### PR DESCRIPTION
**Pull request by kasemAlem**
Added new yamls strategies for presented demos in Release team, 
fixed example and json validation.

### CODE REVIEW

**Comment by kasemAlem** [comment]
@johnbieren @davidmogar @mmalina @theflockers @scoheb 
please review

**Review by scoheb — CHANGES_REQUESTED** [review]
no newlines

**Review by scoheb — CHANGES_REQUESTED** [review]
still missing some new lines

**Comment by kasemAlem** [comment]
Thanks @scoheb 
New lines added and fixed, 
still looking into brew issue

**Review by scoheb — APPROVED** [review]

**Comment by davidmogar** [comment]
Rebase the branch to fetch the fix.

**Pull request merged**
